services:
  go-llvm-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspace
    volumes:
      - .:/workspace
      - go-mod-cache:/go/pkg
      - build-cache:/root/.cache
    command: sh -c "${CMD}"

volumes:
  go-mod-cache:
  build-cache: